project:
  type: website
  output-dir: "docs"

website:
  title: "Adrián Calvo-Valderrama"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: "Portfolio.qmd"
      - text: "CV"
        file: "CV.qmd"
    right:
      - icon: github
        href: https://github.com/adcalvoval
      - icon: twitter-x
        href: https://twitter.com/acalvoval
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

